### PR TITLE
fix: enable source map

### PR DESCRIPTION
**Pull request by pengx17**

### CODE REVIEW

**Review by fi3ework — CHANGES_REQUESTED** [review]
Would you keep the original file structure as https://github.com/open-wc/open-wc/tree/master/packages/dev-server-hmr/src/babel. For example, `packages/dev-server-hmr/src/babel-transform.js` should keep `packages/dev-server-hmr/src/babel/babelTransform.js` as-is. To make the unnecessary modification smaller, we could make it easier to sync the source version from open-wc/dev-server-hmr.

**Comment by pengx17** [comment]
@fi3ework I think one solution is to patch the upstream so that no code is required for this repo. Another solution is to apply a patch after the upstream is cloned.
Or perhaps you could please continue working on my PR for the goal that you proposed?

**Comment by fi3ework** [comment]
Thanks for the git patch solution. But I think it's quite hard to code review and re-edit files for now. I think it's OK to keep the current solution. I just finished the tweak based on your first commit. Do you mind if I made a force-push to this PR or open a new PR with the first commit?

**Comment by pengx17** [comment]
Sure, np :D

**Review by pengx17 — COMMENTED** [review]
:shipit:

**Comment by fi3ework** [comment]
@pengx17 Have a look, does this meet the target now?

**Comment by fi3ework** [comment]
Thanks for the contribution! I'll release a new version soon.

**Comment by pengx17** [comment]
@fi3ework let me know it a new version is published

**Comment by fi3ework** [comment]
@pengx17 0.1.3 is released

**Pull request merged**
